# Generated by Django 3.0.4 on 2020-03-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('likes', models.IntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
